name: milk_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^4.4.0
  table_calendar: ^3.1.3
  calendar_date_picker2: ^2.0.1
  localization: ^2.1.1
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.3
  fl_chart: ^1.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true